### ISSUE TITLE
lemmatizer is too slow

### ISSUE THREAD

**Issue by jmnybl** [TurkuNLP/Turku-neural-parser-pipeline#12]
The current lemmatizer is a major bottleneck for the pipeline speed. We are working on porting the lemmatizer to tensorflow backend which should provide much faster prediction times.

**Comment by jmnybl** [comment]
Fix for this issue committed and merged to master on Dec 14, 2018.

Updated versions of pytorch and opennmt-py increase the lemmatization speed, especially on GPU (lemmatizer is still using pytorch backend). Full pipeline speed on GPU is ~100 trees/sec, and on CPU ~22 trees/sec. The CPU lemmatization speed can be yet increased by collecting a larger lemma cache (by default it's collected from the training data). I'll provide a script for this, as well as pre-collected Finnish cache file soon.

**Comment by jaaqo** [comment]
Hey!

Looks like the server docker (finnish) is having a response time of ~3s for relatively small sentences. Is there anything we can do to optimize this further? For usability we'd be striving for sub 500ms response times.

Thanks a lot for your work so far! There's a real demand for production quality Finnish parsers.

**Comment by fginter** [comment]
In sustained parsing mode on a GPU, the current parser runs at 250-300 sentences per second, which is a perfectly competitive throughput. The response latency is another problem, opened issue #23 for it.
