### ISSUE TITLE
Training a new model?

### ISSUE THREAD

**Issue by aslanerkam** [TurkuNLP/Turku-neural-parser-pipeline#13]
Hi, can you please supply some instructions for training the pipeline?

**Comment by jmnybl** [comment]
Hi,

Good point. I'll try to provide instructions for this soon.

**Comment by erickrf** [comment]
Any news on this?

**Comment by jmnybl** [comment]
I'm working on this right now, I'll try to finish necessary scripts and documentation asap.

**Comment by jmnybl** [comment]
Initial support for training new models provided with latest commits, see https://turkunlp.github.io/Turku-neural-parser-pipeline/training.html for instructions.

Tested to work on Ubuntu 18.04, but this is highly experimental at this stage, please be in touch with pull request/comments in case of troubles.

**Comment by fginter** [comment]
I am aware of multiple people who trained the parser successfully using the provided instructions, so closing this issue for now - it seems the instructions are sufficient to get there with a bit of effort. :laughing:
