### ISSUE TITLE
Docker image hang on OSX and Windows

### ISSUE THREAD

**Issue by spyysalo** [TurkuNLP/Turku-neural-parser-pipeline#15]
When running the docker image following instructions from https://turkunlp.org/Turku-neural-parser-pipeline/docker.html using

    echo "Minulla on koira." | docker run -i turkunlp/turku-neural-parser:finnish-cpu-plaintext-stdin

On a vanilla Docker Desktop (v 2.0.0.3) setup on OSX (v 10.14.3), the parser appears to hang with the last lines of output being

```Bucket parseset-0 is 4 x 6 x 9
Bucket parseset-1 is 4 x 9 x 9
Bucket parseset-2 is 4 x 12 x 9
Bucket parseset-3 is 3 x 14 x 9
Bucket parseset-4 is 3 x 16 x 9
```

(first reported over email)

**Comment by spyysalo** [comment]
This appears to be caused by an out-of-memory issue due to default memory limits on Docker Desktop for Mac (see https://docs.docker.com/docker-for-mac/#advanced). The issue was resolved in our experiments by setting Memory to 4 GB and Swap to 2 GB:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/587850/53815383-3d5b7d00-3f6a-11e9-966d-4c5e99e367f9.png">

**Comment by haamis** [comment]
The same issue occurs on Docker Desktop for Windows. The default amount of memory allocated appears to be 2GB (this is what it was on my machine). Setting memory to 4GB resolves the issue.

![image](https://user-images.githubusercontent.com/3799481/54051861-7ce4cc00-41eb-11e9-8174-9b53ab07297c.png)
