### ISSUE TITLE
Parser does not recognize comments

### ISSUE THREAD

**Issue by kjalonen** [TurkuNLP/Turku-neural-parser-pipeline#16]
Hi,

First of all - thanks for your great work on the parser!

I'm having trouble passing metadata through the parser. As instructed, I marked metadata with the string '###C: ', beginning a new line. However, I found trouble: 

If a document begins with a comment marker, it is not parsed at all (i.e., the resulting CONLL-U is empty), and if comment lines appear after other lines, the parser treats them as it does all other file contents. From the output, it looks like the parser disregards newlines completely, and thus does not recognize the comment markers. (The output .conllu file also does not include any paragraph tags.) However, this doesn’t explain why the parser returns an empty output file for the file that begins with ###C:, instead of passing through the whole file contents unmodified, as a comment.

See the following example:

**INPUT:**
tdf-if

###C: newpar
Suppose we have a set of English text documents[…]

**OUTPUT (abbreviated):**
'# newdoc
'# newpar
'# sent_id = 1
'# text = tdf-if###C: newparSuppose we have a set of English text documents[…]
1    tdf-if###C:    tdf-if###C    PROPN    N
2    newparSuppose    newpar#suppose    NOUN    N  
3    we    we    PROPN    N 
4    have    have    PROPN    N 
5    a    a    PROPN    N    
6    set    set    PROPN    N
7    of    of    PROPN    N
8    English    English    PROPN    N
9    text    text    PROPN    N
10    documents    documents    PROPN    N

I'm running the Finnish server mode Docker image of the parser on OS X.

**Comment by jmnybl** [comment]
Thanks for reporting, I can replicate this with docker server image running on linux. I'll try to fix this today.

**Comment by fginter** [comment]
Was able to replicate. This was the `curl` command stripping the newlines, so the parser saw a single long line. Apparently `--data-binary` is the correct way to call it, not `--data` as was wrongly stated in the instructions. Instructions updated. Thank you for reporting and beta-testing the server mode. :+1:
