### ISSUE TITLE
Lemmatized word with hash signs

### ISSUE THREAD

**Issue by artokarj** [TurkuNLP/Turku-neural-parser-pipeline#22]
It would be more convenient that the lemmatized word would be given without  #-signs. Now one has to build additional logic to determine when the #-signs be replaced with - or dropped to get the actual lemma of the form.

**Comment by fginter** [comment]
The compound markers are used by many who need to separate the compounds for various reasons. Removing the hashes would irreversibly remove information, and prevent these usecases.
