### ISSUE TITLE
Randomly(?) skipping comments

### ISSUE THREAD

**Issue by kauttoj** [TurkuNLP/Turku-neural-parser-pipeline#25]
I'm using comments in my input text to accurately parse the output. This works nicely in general, but I see occasional skipping of comments in my output, which messes up my analysis. I'm using parser image from late August.

Here is an example of input text (an excerpt from a large textfile). Each sentence is separated by a comment with unique ID.

```
...

###C:Di08467Me027Su2

Joo, kiitos vielä.

###C:Di08467Me028Su1

Kiitos, moi moi!

###C:Di08467Me029Su2

Moi moi!

###C:Di08468Me001Su1

Tämä on xxx, kuinka voin auttaa?

###C:Di08468Me002Su2

...
```

Here is the output for that segment (taken from a large file):

```
# Di08467Me027Su2
# newdoc
# newpar
# sent_id = 1
# text = Joo, kiitos vielä.
1	Joo	joo	INTJ	Interj	_	3	discourse	_	SpacesBefore=\r\n|SpaceAfter=No
2	,	,	PUNCT	Punct	_	1	punct	_	_
3	kiitos	kiitos	NOUN	N	Case=Nom|Number=Sing	0	root	_	_
4	vielä	vielä	ADV	Adv	_	3	advmod	_	SpaceAfter=No
5	.	.	PUNCT	Punct	_	3	punct	_	SpacesAfter=\r\n\r\n

# Di08467Me028Su1
# newdoc
# newpar
# sent_id = 1
# text = Kiitos, moi moi!
1	Kiitos	kiitos	NOUN	N	Case=Nom|Number=Sing	0	root	_	SpacesBefore=\r\n|SpaceAfter=No
2	,	,	PUNCT	Punct	_	1	punct	_	_
3	moi	moi	INTJ	Interj	_	1	discourse	_	_
4	moi	moi	INTJ	Interj	_	1	discourse	_	SpaceAfter=No
5	!	!	PUNCT	Punct	_	1	punct	_	SpacesAfter=\r\n\r\n

# newdoc
# newpar
# sent_id = 1
# text = Moi moi!
1	Moi	moi	INTJ	Interj	_	0	root	_	_
2	moi	moi	INTJ	Interj	_	1	fixed	_	SpaceAfter=No
3	!	!	PUNCT	Punct	_	1	punct	_	SpacesAfter=\r\n\r\n

# Di08468Me001Su1
# newdoc
# newpar
# sent_id = 1
# text = Tämä on xxx, kuinka voin auttaa?
1	Tämä	tämä	PRON	Pron	Case=Nom|Number=Sing|PronType=Dem	4	nsubj:cop	_	SpacesBefore=\r\n
2	on	olla	AUX	V	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	4	cop	_	_
...
```

As you see comment "###C:Di08467Me029Su2" was not printed in output, it was simply omitted by the parser. 

Do you know why this happens and is there something I can do to prevent this? Maybe format my input file differently?

**Comment by fginter** [comment]
Hmm. This must be happening somehow during the batching. Can you give some stats on how often this happens and how deep in the file the comments that got dropped are?

**Comment by kauttoj** [comment]
Here are some numbers:
It appears that 600 out of all 450908 comments were missing, which is around 0.13%.

Missing comments were found in all parts of the result file, however not in totally random fashion. Location percentiles of missing comments in the output file were as follows:
```
0.28 (10%)
0.62 (20%)
0.77 (30%)
0.80 (40%)
0.83 (50%) <--- mean location
0.85 (60%)
0.87 (70%)
0.89 (80%)
0.93 (90%)
```
where 0.0 corresponds to the first line and 1.0 the last line. So there appears to be some bias towards the end of file.

**Comment by jmnybl** [comment]
I believe this line causes the error: https://github.com/TurkuNLP/Turku-neural-parser-pipeline/blob/54f86d3d293be267fc17c90bbb539332a8fdca92/full_pipeline_stream.py#L99

I.e. If the input has empty line between the comment and the actual text content, the parser thinks it's okay to split the batch there, resulting in floating comments which cannot be anymore attached to any text segment and will be deleted. I assume that removing the empty line between the comment and text content will resolve the issue, but of course should not be a requirement, and we will look into fixing the issue.

**Comment by kauttoj** [comment]
Ok, thanks for the update. I added those empty lines in order make extra-sure that those lines between comments (which often contain multiple sentences) are always considered as separate paragraphs and never merged. But apparently it just made the situation worse.

**Comment by fginter** [comment]
This should now be fixed in the latest version, also the Docker has been updated to reflect it.
