### ISSUE TITLE
Paper to cite?

### ISSUE THREAD

**Issue by harpaj** [TurkuNLP/Turku-neural-parser-pipeline#3]
Hello! I used your new parser for my research - thanks a lot for open-sourcing it, is was a great help! Which paper would you like me to cite? http://universaldependencies.org/conll17/proceedings/pdf/K17-3012.pdf?

**Comment by jmnybl** [comment]
Hi @harpaj ,

I have now added the reference section with correct bibtex for the parser documentation, see https://turkunlp.github.io/Turku-neural-parser-pipeline/

Thanks,
Jenna

**Comment by harpaj** [comment]
Perfect, thank you!
