### ISSUE TITLE
Unexpected output format

### ISSUE THREAD

**Issue by fjambe** [TurkuNLP/Turku-neural-parser-pipeline#33]
Hi,

I am facing an issue while running the pipeline on Latin (local installation, run on CPU). I trained my own model and I am now trying to run it on a test file, but as output I obtain a CoNLL-U file with only 9 fields, as the fifth (XPOS) and the sixth (feats) ones are merged together.
I tried to run the parser with the pipeline options parse_conllu and parse_ conllu_nolemmas, but in both cases the output has only 9 fields.
When running parse_conllu_nolemmas, I obtain:

```
Runtime: 0:55 [m:s]  Parsed: 2644 [trees], 44752 [tokens]  Speed: 47.75398389100185 [trees/sec]  0.020940661250012003 [sec/tree] 808.2777182640375 [tokens/sec]
Output exiting
```

My file contains exactly 44752 tokens, so apparently the parser works fine, and yet the problem in the output persists, as shown here below.

```
1       hoc     _       1       F1|grn1|casA|gen3               5       Sb      _       _
2       etiam   _       4       O4|vgr1         5       AuxZ    _       _
3       specialiter     _       1       C1|grn1|casG            5       Adv     _       _
```
When running parse_conllu, some additional error seems to occur:

```
 >>> 0/832 lemmas already filled before lemma cache module
 >>> 276/832 lemmatized with lemma cache
Lemma cache exiting
 >>> 143/832 unique tokens submitted to lemmatizer
Lemmatizer exiting
Output exiting
```

Any hint on why it happens?

Thank you!

**Comment by jmnybl** [comment]
Hi,

Could you post here few lines from the training file you are using to show what kind of values you have in each column? I suspect there might be a bug in one of the parser post-processing scripts, and it fails to recognize which values belong to XPOS, and which belong to features.

**Comment by fjambe** [comment]
Sure,

```
7	quod	quod	4	O4	_	3	AuxC	_	_
8	forma	forma	1	A1	grn1|casA|gen2	11	Sb	_	_
9	simplex	simplex	1	C1	grn1|casA|gen2	8	Atr	_	_
10	non	non	4	O4	_	11	AuxZ	_	_
11	potest	possum	3	N3	modA|tem1|gen6	7	Atr	_	_
12	esse	sum	3	N3	modH|tem1	11	Obj	_	_
13	subjectum	subjectum	1	B1	grn1|casA|gen3|vgr1	12	Pnom	_	_
```

**Comment by jmnybl** [comment]
The problem should be fixed now. The change is in the submodule, you should be able to update your local repository with `git pull --recurse-submodules`.

This should not affect the trained models, so you should be able to run all pipelines without retraining the models. However, in case of unexpected evaluation performance, it would be safer to retrain the pipeline.

**Comment by fjambe** [comment]
It works fine now, thank you for your help.
