### ISSUE TITLE
First example in documentation fails with Python 3.8

### ISSUE THREAD

**Issue by ramiluisto** [TurkuNLP/Turku-neural-parser-pipeline#34]
Following the [basic documentation](https://turkunlp.org/Turku-neural-parser-pipeline/) of the pipeline, after installing the python dependencies we are instructed to try the following:

`echo "Minulla on koira." | python3 tnpp_parse.py --conf models_fi_tdt_dia/pipelines.yaml parse_plaintext`

This raises an error at least with Python versions 3.8.5 and 3.8.3. (KeyError in `"/anaconda/envs/example_venv/lib/python3.8/site-packages/diaparser/utils/transform.py", line 117`, somewhat randomly changing which key seems to be missing.)

Using Python 3.6 or 3.7 (3.7.11) seems to work without problems.

**Comment by fginter** [comment]
Thanks, I can replicate this. This seems to be an error in the diaparser library reported here: https://github.com/Unipisa/diaparser/issues/9 ... I posted a fix there now. If it looks like this won't be fixed upstream soon, we will fork diaparser and fix it there. Thank you for reporting. If you are in a hurry, you can apply the fix I posted in the upstream issue. I will check back on this in few days and do the fork solution if needed.

**Comment by fginter** [comment]
I decided not to wait after all. requirements.txt now installs a TurkuNLP fork of diaparser which has been patched. Now tested to work on Py 3.8 and 3.9. Reopen if you still have problems.
