### ISSUE TITLE
Trouble running on Cuda 11 / Ampere / PyTorch 1.9.1

### ISSUE THREAD

**Issue by frankier** [TurkuNLP/Turku-neural-parser-pipeline#35]
I'm having some problems running this on CSC Mahti with the Ampere GPUs. I'm trying to run the STDIN/STDOUT stream entry point.

Here is the image: https://github.com/fshdnc/eb_class/pkgs/container/finnessayscore_tnpp/8686012

Here is the Dockerfile: https://github.com/fshdnc/eb_class/blob/master/Dockerfile.tnpp

It adds the Python module `preproc_tnpp`  into the container - but it's not needed for replication. The main thing is that it's installing PyTorch 1.9.1 for CUDA 11 over the top of the PyTorch from the requirements.

To replicate:

 1. Pull the image using `singularity pull docker://ghcr.io/fshdnc/finnessayscore_tnpp@sha256:39ece6eef49131923553588b45ad3e61226cb2345c1af9f16e5d0fc9b8f88028` or just use `/scratch/project_2004993/frankier/.snakemake/singularity/42a776afe17eed77c941a1f2596859f0.simg`

2. Run sbatch on the following file

```
#!/bin/bash
#SBATCH -t 00:05:00
#SBATCH -p gputest
#SBATCH --ntasks-per-node=1
#SBATCH --mem=8G
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:a100:1
#SBATCH --account=project_2003833

singularity_wrapper exec --nv /path/to/my.sif bash -c 'pwd && echo "Minulla on koira\nMinä pidän voileipäkakusta" | PYTHONPATH=/usr/src/app/ python -m full_pipeline_stream --conf-yaml /usr/src/app/models_fi_tdt_dia/pipelines.yaml --device 0 parse_plaintext'
```

This runs some stuff for a little while and then hangs after about 1 minute. It also seems like it perhaps locks up the GPU since `nvidia-smi` will not run when ssh'ing into the node.

Hopefully this isn't a PyTorch/GPU multiprocessing issue because debugging that is likely to be quite painful. On the other hand, if you have some idea what it is, I can try to take a look.

**Comment by frankier** [comment]
Turns out this was my problem: not allocating enough memory. The OOM killer then kills an individual stage which is using a lot of memory (probably the lemmatiser cache). I added some code to tear the pipeline down in this case https://github.com/TurkuNLP/Turku-neural-parser-pipeline/pull/36

**Comment by fginter** [comment]
Thank you for the PR! Merged
