### ISSUE TITLE
Can't get access to older models

### ISSUE THREAD

**Issue by gshigin** [TurkuNLP/Turku-neural-parser-pipeline#37]
At the moment I can't access the http://bionlp-www.utu.fi/dep-parser-models/ website. I need pretrained model for Russian language. Is there any chance to get them now somehow?

**Comment by fginter** [comment]
Hi, whoops sorry. That machine was firewalled some weeks ago. You can access the old models here: http://epsilon-it.utu.fi/dep-parser-models/
