### ISSUE TITLE
fail with informative message when old pipeline is used with new code

### ISSUE THREAD

**Issue by fginter** [TurkuNLP/Turku-neural-parser-pipeline#6]
Recognize that lemmatizer is run without cache, fail, give informative message. In the future, we should have model metadata to be able to recognize such situations. But no time now.

**Comment by jmnybl** [comment]
Lemma cache is now a separate module. Pipeline fails with an error message if the actual lemmatizer_mod is called with lemma_cache parameter, which probably means pipelines.yaml is not up-to-date and new version of models should be downloaded.
